name: Deploy Booking App (EC2 + S3 + MongoDB Atlas)

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

jobs:

  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      # Build Docker image
      - name: Build backend Docker image
        run: |
          docker build -t $ECR_REPOSITORY ./Booking-Backend

      # Tag image
      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY:latest \
          $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Push image to ECR
      - name: Push Docker image
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-backend

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # SSH into EC2 and deploy container
      - name: Deploy backend on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            echo "Login to ECR"
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

            echo "Stopping old container"
            docker stop backend || true
            docker rm backend || true

            echo "Pull latest image"
            docker pull ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

            echo "Run new container"
            docker run -d \
              --name backend \
              -p 8000:8000 \
              -e MONGODB_URL="${{ secrets.MONGODB_URL }}" \
              -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
              -e ACCESS_TOKEN_EXPIRE_MINUTES="${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}" \
              -e ALGORITHM="${{ secrets.ALGORITHM }}" \
              ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest


      # Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      # Upload frontend to S3
      - name: Upload frontend to S3
        run: |
          aws s3 sync frontend/build s3://booking-app-frontend --delete
